name: inspection_multiple_damage
description: "Multiple Damage Inspection Form."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  intl: ^0.19.0
  pdf: ^3.10.2
  path_provider: ^2.0.14
  shared_preferences: ^2.0.11
  flutter_email_sender: ^6.0.3
  share_plus: ^10.1.4
  share_extend: ^2.0.0
  flutter_localizations:
    sdk: flutter
  flutter_datetime_picker: ^1.5.1
  cupertino_icons: ^1.0.8
  win32: ^5.10.0
  permission_handler: ^11.0.0
  #google_mlkit_text_recognition: ^0.14.0
  image: ^4.0.15
  uuid: ^3.0.6  # Ou a versão mais recente disponível
  signature: ^5.5.0
  firebase_core: ^3.10.1
  firebase_database: ^11.3.1 # Para o banco de dados
  firebase_storage: ^12.4.1  # Para as fotos
  cloud_firestore: ^5.6.2
  http: ^1.3.0
  connectivity_plus: ^6.1.3
  flutter_local_notifications: ^18.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.3"

flutter:
  uses-material-design: true
  
  assets:
    - assets/logo_cliente.png
    - assets/email_icon.png
    - assets/location_icon.png
    - assets/phone_icon.png
    - assets/instagram_icon.png
    - assets/website_icon.png

flutter_icons:
  image_path: "assets/appicon.png"
  android: true 
  ios: true
  adaptive_icon_background: "#FFFFFF" # Cor de fundo ou imagem de fundo
  adaptive_icon_foreground: "assets/appicon.png" # Ícone principal, sem espaço em branco
